ALTER TABLE transactions 
ADD COLUMN currency VARCHAR(10) NOT NULL DEFAULT 'IDR',
ADD COLUMN geo_lat NUMERIC(10,7),
ADD COLUMN geo_lng NUMERIC(10,7),
ADD COLUMN geo_name VARCHAR(255);

ALTER TABLE scheduled_transactions 
ADD COLUMN currency VARCHAR(10) NOT NULL DEFAULT 'IDR',
ADD COLUMN last_run TIMESTAMP;
