CREATE TABLE IF NOT EXISTS tag_groups (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    name VARCHAR(100) NOT NULL,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE tags
ADD COLUMN group_id UUID REFERENCES tag_groups(id) ON DELETE SET NULL,
ADD COLUMN sort_order INT DEFAULT 0;
