basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: dev@finvera.app
    name: Finvera Dev Team
  description: REST API untuk aplikasi keuangan Finvera - Personal Finance Manager
  title: Finvera API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    description: 'Masukkan token JWT dengan format: Bearer {token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
